var res = {
    HelloWorld_png: "res/HelloWorld.png",
    CloseNormal_png: "res/CloseNormal.png",
    CloseSelected_png: "res/CloseSelected.png",
    boton_jugar_png: "res/boton_jugar.png",
    boton_reanudar_png: "res/boton_reanudar.png",
    menu_titulo_png: "res/hill_climb_menu.jpg",
    tiles32_png: "res/tiles32.png",
    mapa1_tmx: "res/mapa1.tmx",
    mapa2_tmx: "res/mapa2.tmx",
    mapa3_tmx: "res/mapa3.tmx",
    moneda_png : "res/moneda.png",
    moneda_plist : "res/moneda.plist",
    moneda1_png : "res/moneda1.png",
    playerrunright_png : "res/playerrunright.png",
    playerrunright_plist : "res/playerrunright.plist",
    playerjumpright_png : "res/playerjumpright.png",
    playerjumpright_plist : "res/playerjumpright.plist",
    playeridleright_png : "res/playeridleright.png",
    playeridleright_plist : "res/playeridleright.plist",
    playerdieright_png : "res/playerdieright.png",
    playerdieright_plist : "res/playerdieright.plist",
    disparo_png : "res/disparo.png",
    disparo_plist : "res/disparo.plist",
    playershootright_png : "res/playershootright.png",
    playershootright_plist : "res/playershootright.plist",
    animacion_cuervo_png: "res/animacion_cuervo.png",
    animacion_cuervo_plist: "res/animacion_cuervo.plist",
    disparo_png: "res/disparo.png",
    disparo_plist: "res/disparo.plist",
    playershootright_png: "res/playershootright.png",
    playershootright_plist: "res/playershootright.plist",
    spritesheet_complete_png: "res/spritesheet_complete.png",
    mapa_tmx: "res/mapa.tmx",

    //Resources from hill climb

    boy_body: "res/boy_body.png",
    boy_head: "res/boy_head.png",
    cars: "res/cars.png",
    girl_body: "res/girl_body.png",
    girl_head: "res/girl_head.png",
    orc_body: "res/orc_body.png",
    orc_head: "res/orc_head.png",
    wheel_1: "res/wheel_1.png",
    wheel_2: "res/wheel_2.png",
    wheel_3: "res/wheel_3.png",
    wheel_4: "res/wheel_4.png",
    wheel_5: "res/wheel_5.png",
    wheel_6: "res/wheel_6.png",
    orc_car_png: "res/orc_car.png",
    orc_car_plist: "res/orc_car.plist",
    gas_pedal: "res/gas_pedal.png",
    brake_pedal: "res/brake_pedal.png",
    gas_tank: "res/gas_tank.png",
    gas: "res/gas.png",
    gas_plist : "res/gas.plist",
    spritesheet : "res/spritesheet.png",
    flag_png : "res/flag.png",
    progressBar_png: "res/progressBar.png",
    animacion_mina_normal_png : "res/animacion_mina_normal.png",
    animacion_mina_normal_plist : "res/animacion_mina_normal.plist",
    animacion_mina_explota_png : "res/animacion_mina_explota.png",
    animacion_mina_explota_plist : "res/animacion_mina_explota.plist",
    animacion_cocodrilo_plist : "res/animacion_cocodrilo.plist",
    animacion_cocodrilo_png : "res/animacion_cocodrilo.png",
    caja_png : "res/caja.png",
    caja_plist : "res/caja.plist",
    rana_png : "res/rana.png",
    rana_plist : "res/rana.plist",
    tabla_h: "res/tabla_h.png",
    tabla_v: "res/tabla_v.png",
    tabla_png : "res/tabla.png",
    tabla_plist : "res/tabla.plist",
    powerup_png : "res/powerup.png",
    powerup_plist : "res/powerup.plist",
    seleccion_nivel_png : "res/seleccion_nivel.png",
    nivel1_png : "res/nivel1.jpg",
    nivel2_png : "res/nivel2.jpg",
    nivel3_png : "res/nivel3.jpg",
    bandera_png : "res/bandera.png",
    bandera_plist : "res/bandera.plist"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}